// Code generated by github.com/xySaad/cfgo; DO NOT EDIT.
package example

import (
	 "github.com/joho/godotenv"
	 "os"
	
)
func init() {
var err error
err = godotenv.Load(".env");if err != nil {panic(err)}
}

type Graphql struct {
	Login_api string
	Username string
	Password string
}

var graphql = Graphql{
	Login_api: "https://learn.zone01oujda.ma/api/auth/signin",
	Username: "java",
	Password: os.Getenv("GRAPHQL_PASSWORD"),
}

func GetGraphql() Graphql { return graphql }

type Client struct {
	Secret string
	Id string
}

var client = Client{
	Secret: os.Getenv("GITEA_CLIENT_SECRET"),
	Id: "0deb28b4-d8bc-45a0-a6dc-564de08325ae",
}

func GetClient() Client { return client }

type Gitea struct {
	Client Client
	Endpoint string
	User string
	Oauth string
	Redirect_uri string
}

var gitea = Gitea{
	Client: client,
	Endpoint: "https://learn.zone01oujda.ma/git",
	User: "https://learn.zone01oujda.ma/git/api/v1/user",
	Oauth: "https://learn.zone01oujda.ma/git/login/oauth/authorize",
	Redirect_uri: "https://01auth.undo.it/api/auth/callback",
}

func GetGitea() Gitea { return gitea }

type Config struct {
	Address string
	Domain string
	Graphql Graphql
	Gitea Gitea
}

var config = Config{
	Address: "0.0.0.0:5051",
	Domain: "https://learn.zone01oujda.ma",
	Graphql: graphql,
	Gitea: gitea,
}

func GetConfig() Config { return config }
