// Code generated by github.com/xySaad/cfgo; DO NOT EDIT.
package config

import (
	 "github.com/joho/godotenv"
	
)
func mustLoadEnv(path string) map[string]string {
	env, err := godotenv.Read(path)
	if err != nil {
		panic(err)
	}
	return env
}
var env_ENV = mustLoadEnv(".env")
type Graphql struct {
	Username string
	Password string
	Login_api string
}

var graphql = Graphql{
	Username: "java",
	Password: env_ENV["GRAPHQL_PASSWORD"],
	Login_api: "https://learn.zone01oujda.ma/api/auth/signin",
}

func GetGraphql() Graphql { return graphql }

type Client struct {
	Secret string
	Id string
}

var client = Client{
	Secret: env_ENV["GITEA_CLIENT_SECRET"],
	Id: "0deb28b4-d8bc-45a0-a6dc-564de08325ae",
}

func GetClient() Client { return client }

type Gitea struct {
	Endpoint string
	User string
	Oauth string
	Redirect_uri string
	Client Client
}

var gitea = Gitea{
	Endpoint: "https://learn.zone01oujda.ma/git",
	User: "https://learn.zone01oujda.ma/git/api/v1/user",
	Oauth: "https://learn.zone01oujda.ma/git/login/oauth/authorize",
	Redirect_uri: "https://01auth.undo.it/api/auth/callback",
	Client: client,
}

func GetGitea() Gitea { return gitea }

type Config struct {
	Address string
	Domain string
	Graphql Graphql
	Gitea Gitea
}

var config = Config{
	Address: "0.0.0.0:5051",
	Domain: "https://learn.zone01oujda.ma",
	Graphql: graphql,
	Gitea: gitea,
}

func GetConfig() Config { return config }
