// Code generated by github.com/xySaad/cfgo; DO NOT EDIT.
package main

import (
	 "github.com/joho/godotenv"
	 "os"
	
)
func init() {
var err error
err = godotenv.Load("ENV");if err != nil {panic(err)}
}

type Graphql struct {
	Username string
	Password string
	Login_api string
}

var graphql = Graphql{
	Username: "java",
	Password: os.Getenv("GRAPHQL_PASSWORD"),
	Login_api: "${domain}/api/auth/signin",
}

func GetGraphql() Graphql { return graphql }

type Client struct {
	Secret string
	Id string
}

var client = Client{
	Secret: os.Getenv("GITEA_CLIENT_SECRET"),
	Id: "0deb28b4-d8bc-45a0-a6dc-564de08325ae",
}

func GetClient() Client { return client }

type Gitea struct {
	Redirect_uri string
	Client Client
	Endpoint string
	User string
	Oauth string
}

var gitea = Gitea{
	Redirect_uri: "https://01auth.undo.it/api/auth/callback",
	Client: client,
	Endpoint: "https://learn.zone01oujda.ma/git",
	User: "${gitea.endpoint}/api/v1/user",
	Oauth: "${gitea.endpoint}/login/oauth/authorize",
}

func GetGitea() Gitea { return gitea }

type Config struct {
	Address string
	Domain string
	Graphql Graphql
	Gitea Gitea
}

var config = Config{
	Address: "0.0.0.0:5051",
	Domain: "https://learn.zone01oujda.ma",
	Graphql: graphql,
	Gitea: gitea,
}

func GetConfig() Config { return config }
