package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/xySaad/cfgo/models"
	"github.com/xySaad/cfgo/parser"
)

func main() {
	input := os.Args[1]
	output := os.Args[2]

	bfile, err := os.ReadFile(input)
	if err != nil {
		panic(err)
	}

	filePathNoExt := strings.TrimSuffix(input, filepath.Ext(input))
	mappedJSON := map[string]any{}
	err = json.Unmarshal(bfile, &mappedJSON)
	if err != nil {
		panic(err)
	}

	structTempl, err := template.New("struct").Parse(models.STRUCT_TEMPLATE)
	if err != nil {
		panic(err)
	}

	packageName := filepath.Base(filepath.Dir(output))
	if packageName == "." || packageName == string(filepath.Separator) {
		packageName = "main"
	}

	fileName := filepath.Base(filePathNoExt)
	p := parser.NewParser(structTempl)
	buffer := bytes.NewBuffer(nil)
	p.ParseTopLevelImports(mappedJSON)
	p.ParseJSON(fileName, mappedJSON, buffer)
	finalBuf := bytes.NewBufferString("// Code generated by github.com/xySaad/cfgo; DO NOT EDIT.\n")
	fmt.Fprintln(finalBuf, "package", packageName)

	if len(p.Imports()) > 0 {
		importsTempl, err := template.New("imports").Parse(models.IMPORTS_TEMPLATE)
		if err != nil {
			panic(err)
		}
		importsTempl.Execute(finalBuf, p.Imports())
	}

	if len(p.ConfigImports()) > 0 {
		//assume all are .env
		finalBuf.WriteString("\nfunc init() {\nvar err error\n")
		for file := range p.ConfigImports() {
			fmt.Fprintf(finalBuf, "err = godotenv.Load(\"%s\");if err != nil {panic(err)}\n", file)
		}
		finalBuf.WriteString("}\n")
	}

	buffer.WriteTo(finalBuf)
	err = os.WriteFile(output, finalBuf.Bytes(), 0644)
	if err != nil {
		panic(err)
	}
}
