package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/xySaad/cfgo/models"
	"github.com/xySaad/cfgo/parser"
)

func main() {
	switch len(os.Args) {
	case 1: // default config folder 'config/'
		ConvertDirectory("config")
	case 2:
		ConvertDirectory(os.Args[1])
	case 3:
		input := os.Args[1]
		output := os.Args[2]
		packageName := filepath.Base(filepath.Dir(output))
		if packageName == "." || packageName == string(filepath.Separator) {
			packageName = "main"
		}
		Cfgo(input, output, packageName)
	}

}

func ConvertDirectory(dirName string) {
	dir, err := os.ReadDir(dirName)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return
	}
	generatedDir := dirName + "/generated"

	err = os.MkdirAll(generatedDir, 0o755)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return
	}

	for _, entry := range dir {
		if entry.IsDir() {
			// TODO: support nested configs
			continue
		}
		fileName := entry.Name()
		inputExt := filepath.Ext(fileName)
		if inputExt != ".json" {
			continue
		}

		outputFile := fileName[:len(fileName)-len(inputExt)] + ".go"
		output := filepath.Join(generatedDir, outputFile)
		input := filepath.Join(dirName, fileName)

		Cfgo(input, output, filepath.Base(dirName))
	}

}

func Cfgo(input, output, packageName string) {
	bfile, err := os.ReadFile(input)
	if err != nil {
		panic(err)
	}

	filePathNoExt := strings.TrimSuffix(input, filepath.Ext(input))
	mappedJSON := map[string]any{}
	err = json.Unmarshal(bfile, &mappedJSON)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s: %s\n", input, err)
		return
	}

	structTempl, err := template.New("struct").Parse(models.STRUCT_TEMPLATE)
	if err != nil {
		panic(err)
	}

	fileName := filepath.Base(filePathNoExt)
	p := parser.NewParser(mappedJSON, structTempl)
	buffer := bytes.NewBuffer(nil)
	p.ParseTopLevelImports(mappedJSON)
	p.Parse(fileName, buffer)
	finalBuf := bytes.NewBufferString("// Code generated by github.com/xySaad/cfgo; DO NOT EDIT.\n")
	fmt.Fprintln(finalBuf, "package", packageName)

	if len(p.Imports()) > 0 {
		importsTempl, err := template.New("imports").Parse(models.IMPORTS_TEMPLATE)
		if err != nil {
			panic(err)
		}
		importsTempl.Execute(finalBuf, p.Imports())
	}

	if len(p.ConfigImports()) > 0 {
		//assume all are .env

		envLoader, err := template.New("envLoader").Parse(models.ENV_LOADER_TEMPLATE)
		if err != nil {
			panic(err)
		}
		envLoader.Execute(finalBuf, nil)
		for name, file := range p.ConfigImports() {
			fmt.Fprintf(finalBuf, `var env_%s = mustLoadEnv("%s")`, name, file)
		}
	}

	buffer.WriteTo(finalBuf)
	err = os.WriteFile(output, finalBuf.Bytes(), 0644)
	if err != nil {
		panic(err)
	}
}
